-- Quiz questions - 10 questions per medical system (100 total)
BEGIN TRANSACTION;

-- Cardiology Questions
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('acs', 'A 55-year-old male presents with central chest pain radiating to left arm, diaphoresis, and dyspnea. ECG shows ST elevation in leads II, III, aVF. What is the most likely diagnosis and immediate management?', 'Diagnosis: Inferior STEMI. Immediate management: Aspirin 300mg, sublingual nitroglycerin, immediate thrombolysis or PCI, door-to-balloon < 90 min', 'management'),
('acs', 'A 65-year-old diabetic patient presents with atypical chest discomfort. ECG shows ST depression in V1-V4 and elevated troponin. What is this condition and how is it managed?', 'Diagnosis: NSTEMI. Management: Antiplatelet therapy, anticoagulation, early invasive strategy with coronary angiography, medical stabilization', 'management'),
('dka', 'A 25-year-old known type 1 diabetic presents with vomiting, abdominal pain, and Kussmaul breathing. Lab shows glucose 450 mg/dL, pH 7.15, bicarbonate 12 mEq/L. What is the diagnosis and initial fluid management?', 'Diagnosis: DKA. Initial management: 0.9% saline 15-20 mL/kg in first hour, then insulin infusion 0.1 units/kg/hour after potassium > 3.3 mEq/L', 'management'),
('anaemia', 'A 30-year-old female presents with fatigue, pallor, and koilonychia. CBC shows Hb 8 g/dL, MCV 68 fL, ferritin 8 ng/mL. What is the most likely diagnosis and treatment?', 'Diagnosis: Iron deficiency anemia. Treatment: Oral ferrous sulfate 325 mg TID with vitamin C, dietary counseling, repeat CBC in 4 weeks', 'management'),
('stroke', 'A 70-year-old patient presents with sudden right-sided weakness and speech difficulty. NIHSS score is 12. Symptoms started 2 hours ago. What is the immediate management?', 'Immediate management: CT head to exclude hemorrhage, consider IV thrombolysis with alteplase if within 4.5 hour window, blood pressure control if >185/110', 'management'),
('stroke', 'A patient presents with facial drooping, arm weakness, and speech difficulty. What mnemonic is used for stroke recognition and what is the time window for thrombolysis?', 'FAST: Face, Arms, Speech, Time. Thrombolysis window: 4.5 hours from symptom onset for IV alteplase', 'data-interpretation'),
('acs', 'A patient presents with acute chest pain. ECG shows tall peaked T waves, wide QRS complexes, and absent P waves. What electrolyte abnormality is suggested and what are the ECG findings?', 'Hyperkalemia. ECG findings: Peaked T waves (mild), PR prolongation and flattened P waves (moderate), widened QRS and absent P waves (severe), sine wave pattern (very severe)', 'data-interpretation'),
('acs', 'A 45-year-old patient presents with palpitations. ECG shows irregularly irregular rhythm with no P waves, heart rate 130 bpm. What is the diagnosis and initial management?', 'Diagnosis: Atrial fibrillation with rapid ventricular response. Management: Rate control with beta-blockers or calcium channel blockers, anticoagulation assessment, rhythm control consideration', 'management'),
('dka', 'A DKA patient on insulin infusion develops glucose of 250 mg/dL with anion gap of 18. What does this indicate and how should management be adjusted?', 'Indicates resolution of DKA (anion gap closed). Management: Continue insulin, add dextrose to IV fluids when glucose < 250 mg/dL, transition to subcutaneous insulin', 'management'),
('anaemia', 'A patient has macrocytic anemia with MCV 105 fL. What are the common causes and what initial tests should be ordered?', 'Common causes: B12 deficiency, folate deficiency, hypothyroidism, liver disease, alcohol. Initial tests: B12 level, folate level, TSH, LFTs', 'data-interpretation');

-- Respiratory Questions
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('pneumonia', 'A 70-year-old presents with fever, cough productive of rust-colored sputum, and right lower lobe crackles. CXR shows consolidation. CURB-65 score is 3. What does this score indicate and what is the management?', 'CURB-65 of 3 indicates high mortality risk requiring hospital admission. Management: IV antibiotics (ceftriaxone + macrolide), oxygen saturation monitoring, consider ICU', 'management'),
('pneumonia', 'A 45-year-old otherwise healthy patient presents with community-acquired pneumonia. What is the recommended empirical antibiotic therapy?', 'For healthy outpatient: Amoxicillin 1g TID OR doxycycline 100mg BID OR macrolide (azithromycin 500mg daily) for 5-7 days', 'management'),
('pneumonia', 'A patient with pneumonia has SpO2 88% on room air. What is the severity classification and what oxygen therapy should be provided?', 'Severe pneumonia with hypoxemia. Oxygen therapy: Nasal cannula at 2-6 L/min to maintain SpO2 ≥92%, consider high-flow nasal cannula if inadequate', 'management'),
('pneumonia', 'What are the typical chest X-ray findings in lobar pneumonia and how do they differ from interstitial pneumonia?', 'Lobar pneumonia: Airspace consolidation with air bronchograms, well-defined margins following lobar anatomy. Interstitial pneumonia: Reticular pattern, diffuse infiltrates, no air bronchograms', 'data-interpretation'),
('pneumonia', 'A 65-year-old COPD patient presents with pneumonia. What are the recommended antibiotic choices and why?', 'Recommended: Amoxicillin-clavulanate OR respiratory fluoroquinolone OR 3rd generation cephalosporin + macrolide. Need broader coverage due to risk of resistant organisms and H. influenzae', 'management'),
('pneumonia', 'A patient fails to improve after 72 hours of appropriate antibiotic therapy for pneumonia. What are the possible causes and next steps?', 'Possible causes: Wrong pathogen, resistant organism, complication (empyema, abscess), non-infectious mimic. Next steps: Repeat CXR, consider CT, sputum culture, change antibiotics, chest tube if effusion', 'management'),
('pneumonia', 'What are the major criteria for severe community-acquired pneumonia requiring ICU admission?', 'Major criteria: Invasive mechanical ventilation, septic shock requiring vasopressors. Minor criteria: Respiratory rate ≥30, PaO2/FiO2 ≤250, multilobar infiltrates, confusion, BUN ≥20, thrombocytopenia, hypothermia, hypotension', 'data-interpretation'),
('pneumonia', 'A 30-year-old patient presents with atypical pneumonia. What organisms are commonly involved and what are the typical clinical features?', 'Common organisms: Mycoplasma pneumoniae, Chlamydophila pneumoniae, Legionella pneumophila. Features: Gradual onset, headache, myalgias, dry cough, minimal chest findings', 'data-interpretation'),
('pneumonia', 'What is the recommended duration of antibiotic therapy for uncomplicated community-acquired pneumonia?', 'Duration: Minimum 5 days, patient should be afebrile for 48-72 hours and clinically stable before discontinuation. Typical course: 5-7 days', 'management'),
('pneumonia', 'A patient with HIV presents with pneumonia. What additional organisms should be considered and what prophylaxis is recommended?', 'Additional organisms: Pneumocystis jirovecii, atypical mycobacteria, fungi. Prophylaxis: TMP-SMX for PCP when CD4 < 200 cells/μL', 'management');

-- GI & Hepatology Questions
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('dka', 'A patient presents with upper GI bleeding. What are the initial steps in management and what medications should be given?', 'Initial steps: ABCs, large-bore IV access, fluid resuscitation, blood transfusion if Hb < 7 g/dL. Medications: PPI infusion (omeprazole 80 mg bolus then 8 mg/hour), octreotide if variceal bleeding suspected', 'management'),
('dka', 'A 45-year-old alcoholic presents with hematemesis. What is the most likely cause and what endoscopic findings are expected?', 'Most likely: Mallory-Weiss tear or esophageal varices. Endoscopic findings: Linear mucosal tear at GE junction (Mallory-Weiss) or dilated esophageal veins with red wale signs (varices)', 'data-interpretation'),
('dka', 'A patient has chronic hepatitis B with HBV DNA 20,000 IU/mL, ALT 120 U/L, no fibrosis. What is the indication for treatment and what are the first-line options?', 'Treatment indication: HBV DNA > 20,000 IU/mL with elevated ALT. First-line: Tenofovir disoproxil fumarate 300 mg daily OR tenofovir alafenamide 25 mg daily OR entecavir 0.5 mg daily', 'management'),
('dka', 'A patient with cirrhosis presents with ascites and mild hepatic encephalopathy. What are the key components of management?', 'Management: Sodium restriction <2 g/day, diuretics (spironolactone + furosemide), lactulose for encephalopathy, avoid sedatives, monitor for spontaneous bacterial peritonitis', 'management'),
('dka', 'What are the Child-Pugh criteria for assessing severity of cirrhosis and what do they indicate?', 'Child-Pugh criteria: Bilirubin, albumin, INR, ascites, encephalopathy. Class A (5-6): Good prognosis, Class B (7-9): Moderate, Class C (10-15): Poor prognosis', 'data-interpretation'),
('dka', 'A patient presents with acute pancreatitis. What are the Ranson criteria and what score indicates severe disease?', 'Ranson criteria: At admission - age >55, WBC >16,000, glucose >200, LDH >350, AST >250. At 48 hours - Hct drop >10%, calcium <8 mg/dL, PaO2 <60, base deficit >4, fluid sequestration >6L. Score ≥3 indicates severe disease', 'data-interpretation'),
('dka', 'A patient has dyspepsia refractory to PPI therapy. What are the alarm symptoms and what investigation is recommended?', 'Alarm symptoms: Weight loss, dysphagia, odynophagia, vomiting, GI bleeding, anemia, mass, family history of cancer. Investigation: Upper GI endoscopy', 'management'),
('dka', 'What is the recommended treatment for H. pylori infection and what is the test of cure?', 'Recommended treatment: Triple therapy (PPI + clarithromycin 500 mg BID + amoxicillin 1g BID) for 14 days OR quadruple therapy (PPI + bismuth + tetracycline + metronidazole). Test of cure: Urea breath test or stool antigen 4 weeks after completion', 'management'),
('dka', 'A patient with inflammatory bowel disease presents with severe ulcerative colitis. What are the indications for hospitalization and what is the initial medical therapy?', 'Hospitalization indications: >6 bloody stools/day, fever, tachycardia, anemia, ESR >30, hypoalbuminemia. Initial therapy: IV steroids (methylprednisolone 40-60 mg daily), consider infliximab or colectomy if no response in 3-5 days', 'management'),
('dka', 'A patient has acute cholecystitis. What are the Tokyo guidelines for severity grading and what is the management for each grade?', 'Grade I (mild): Laparoscopic cholecystectomy within 24 hours. Grade II (moderate): Same but may need gallbladder drainage. Grade III (severe): ICU care, urgent gallbladder drainage, delayed cholecystectomy', 'management');

-- Nephrology Questions
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('uti', 'A 25-year-old female presents with dysuria, frequency, and suprapubic pain. Urine dipstick shows 2+ leukocyte esterase, 2+ nitrites. What is the diagnosis and treatment?', 'Diagnosis: Uncomplicated cystitis. Treatment: Nitrofurantoin 100 mg BID for 5 days OR TMP-SMX DS BID for 3 days OR fosfomycin single dose', 'management'),
('uti', 'A 70-year-old male with BPH presents with fever, chills, and flank pain. What is the diagnosis and what imaging is recommended?', 'Diagnosis: Complicated UTI/pyelonephritis. Imaging: Renal ultrasound or CT to evaluate for obstruction, abscess, or stones', 'management'),
('uti', 'A patient with recurrent UTIs has 3 infections in 6 months. What preventive measures are recommended?', 'Prevention: Post-coital voiding, increased fluid intake, cranberry products, topical estrogen for postmenopausal women, consider prophylactic antibiotics (TMP-SMX or nitrofurantoin)', 'management'),
('uti', 'What are the criteria for diagnosing acute kidney injury according to KDIGO guidelines?', 'KDIGO AKI criteria: Increase in serum creatinine by ≥0.3 mg/dL within 48 hours OR increase to ≥1.5 times baseline within 7 days OR urine output <0.5 mL/kg/h for 6 hours', 'data-interpretation'),
('uti', 'A patient with CKD stage 3 has eGFR 45 mL/min/1.73m². What are the management priorities and medication adjustments needed?', 'Management: Blood pressure control <130/80, proteinuria reduction with ACEi/ARB, avoid nephrotoxins, manage complications. Med adjustments: Adjust doses for renally cleared drugs, avoid NSAIDs, use metformin if eGFR >30', 'management'),
('uti', 'A patient presents with nephrotic syndrome (proteinuria >3.5 g/day, albumin <3 g/dL, edema). What are the common causes in adults and initial workup?', 'Common causes: Minimal change disease, FSGS, membranous nephropathy, diabetic nephropathy. Workup: Urine protein/creatinine ratio, serum albumin, lipid profile, viral hepatitis screen, ANA, complement levels, consider renal biopsy', 'data-interpretation'),
('uti', 'What are the indications for initiating dialysis in CKD patients?', 'Indications: eGFR <10 mL/min/1.73m² (or <15 with symptoms), uremic symptoms (nausea, pericarditis, encephalopathy), refractory volume overload, severe metabolic acidosis, hyperkalemia >6.5 mEq/L', 'management'),
('uti', 'A patient with polycystic kidney disease presents with hematuria. What are the potential causes and management approach?', 'Causes: Cyst rupture, kidney stones, infection, renal cell carcinoma. Management: CT urogram to evaluate, treat infection if present, monitor for malignancy, control blood pressure', 'management'),
('uti', 'What are the target blood pressure goals for patients with CKD and proteinuria?', 'Target: <130/80 mmHg for CKD patients with proteinuria >300 mg/day. First-line: ACE inhibitor or ARB for proteinuria reduction, monitor for hyperkalemia and creatinine rise', 'management'),
('uti', 'A patient presents with hyperkalemia of 7.2 mEq/L with ECG changes. What is the emergency management?', 'Emergency management: Calcium gluconate 10% 10 mL IV over 2-3 minutes, then insulin + dextrose, nebulized albuterol, sodium bicarbonate if acidotic, prepare for dialysis if refractory', 'management');

-- Neurology Questions
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('stroke', 'A patient presents with sudden onset of worst headache of life. What is the most concerning diagnosis and what is the initial investigation?', 'Most concerning: Subarachnoid hemorrhage. Initial investigation: Non-contrast CT head (sensitivity >95% in first 6 hours), if negative consider lumbar puncture', 'management'),
('stroke', 'What are the contraindications for IV thrombolysis in acute ischemic stroke?', 'Contraindications: Intracranial hemorrhage, recent intracranial surgery, known AVM, uncontrolled hypertension (>185/110), recent major surgery/trauma, GI/GU hemorrhage within 21 days, INR >1.7, platelets <100,000', 'data-interpretation'),
('stroke', 'A patient has new onset seizures. What are the initial investigations and when should antiepileptic medication be started?', 'Investigations: CBC, electrolytes, glucose, renal/hepatic function, toxicology screen, EEG, brain imaging (CT/MRI). Start AED after second seizure or if status epilepticus, structural abnormality, or high risk of recurrence', 'management'),
('stroke', 'What are the clinical features of Parkinson''s disease and what are the first-line treatments?', 'Features: Bradykinesia, resting tremor, rigidity, postural instability. First-line: Levodopa + carbidopa, dopamine agonists (pramipexole, ropinirole) for younger patients, MAO-B inhibitors for early disease', 'management'),
('stroke', 'A patient presents with acute confusion and agitation. What is the differential diagnosis and initial assessment?', 'Differential: Delirium, dementia, stroke, metabolic encephalopathy, infection, medication toxicity. Assessment: ABCs, glucose, vitals, neurological exam, CAM-ICU for delirium assessment, basic labs, consider CT if focal findings', 'management'),
('stroke', 'What are the warning signs of meningitis that should prompt immediate evaluation and empiric treatment?', 'Warning signs: Fever, headache, neck stiffness, photophobia, altered mental status, petechial rash. Empiric treatment: Ceftriaxone 2g IV q12h + vancomycin + dexamethasone before lumbar puncture if suspected', 'management'),
('stroke', 'A patient has migraine headaches with aura. What are the typical aura symptoms and acute treatment options?', 'Aura symptoms: Visual (scintillating scotoma, fortification spectra), sensory (numbness, tingling), motor weakness, language disturbance. Acute treatment: NSAIDs, triptans, antiemetics, avoid ergotamines with aura', 'management'),
('stroke', 'What are the clinical features of multiple sclerosis and what disease-modifying therapies are available?', 'Features: Relapsing-remitting course, optic neuritis, internuclear ophthalmoplegia, sensory level, Uhthoff phenomenon. DMTs: Interferon-beta, glatiramer acetate, dimethyl fumarate, fingolimod, natalizumab, ocrelizumab', 'management'),
('stroke', 'A patient presents with Bell''s palsy. What is the initial management and what are the red flag features?', 'Initial management: Eye protection (lubricating drops, tape), oral prednisone 60-80 mg daily for 5-7 days within 72 hours. Red flags: Slow onset, facial weakness with other neurological signs, inability to close eye completely, recurrent palsy', 'management'),
('stroke', 'What are the clinical features of Guillain-Barré syndrome and what monitoring is required?', 'Features: Ascending paralysis, areflexia, mild sensory changes, autonomic dysfunction, respiratory failure risk. Monitoring: Serial vital capacity, FVC, cardiac monitoring for arrhythmias, ICU transfer if FVC <20 mL/kg or dysautonomia', 'management');

-- Infectious Disease Questions
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('dengue', 'A patient presents with dengue fever. What are the warning signs for severe dengue requiring hospitalization?', 'Warning signs: Severe abdominal pain, persistent vomiting, clinical fluid accumulation, mucosal bleeding, lethargy/restlessness, liver enlargement >2 cm, rapid increase in hematocrit with rapid decrease in platelets', 'data-interpretation'),
('dengue', 'What is the fluid management strategy for dengue shock syndrome?', 'Fluid management: Immediate IV access, rapid bolus 20 mL/kg over 20 minutes, repeat if still in shock (max 3 boluses), then maintenance fluids 2-3 mL/kg/hour, monitor for overload', 'management'),
('dengue', 'A patient has platelet count of 25,000 with active bleeding. What is the management?', 'Management: Hospital admission, platelet transfusion 1 unit/10 kg, consider cryoprecipitate if coagulopathy, monitor for severe bleeding, avoid NSAIDs', 'management'),
('typhoid', 'What are the typical Widal test interpretations for typhoid fever?', 'Interpretation: Single titer O ≥1:160 or H ≥1:160 suggests active infection, four-fold rise in paired samples more reliable, false positives common in endemic areas, vaccinated individuals', 'data-interpretation'),
('typhoid', 'A patient with typhoid fever develops intestinal perforation. What is the emergency management?', 'Emergency management: Immediate surgical consultation, NPO status, NG tube, broad-spectrum antibiotics (ceftriaxone + metronidazole), aggressive fluid resuscitation, urgent surgical repair', 'management'),
('malaria', 'A patient has P. falciparum malaria with parasitemia of 8%. What is the severity classification and treatment?', 'Classification: Severe malaria (parasitemia >5%). Treatment: IV artesunate 2.4 mg/kg at 0, 12, 24 hours then daily, consider exchange transfusion if >10%, monitor for complications', 'management'),
('malaria', 'What are the complications of severe malaria and their specific management?', 'Complications: Cerebral malaria (seizure control, ICP management), severe anemia (transfusion Hb <5), renal failure (hydration, dialysis), hypoglycemia (dextrose infusion), pulmonary edema (diuretics, ventilation)', 'management'),
('cholera', 'A patient presents with profuse watery diarrhea ("rice-water stool"). What is the initial management?', 'Initial management: Rapid rehydration with ORS, if severe dehydration or vomiting - IV Ringer lactate, start antibiotics (doxycycline 300 mg single dose or azithromycin 1g), zinc supplementation', 'management'),
('cholera', 'What are the WHO criteria for severe dehydration in cholera?', 'Criteria: Lethargy/unconsciousness, sunken eyes, unable to drink or drinking poorly, skin pinch goes back very slowly (>2 seconds). Requires immediate IV fluid resuscitation', 'data-interpretation'),
('dengue', 'What is the recommended discharge criteria for dengue fever?', 'Discharge criteria: Afebrile for 48 hours without antipyretics, platelet count >50,000 with rising trend, no warning signs, adequate oral intake, stable hematocrit', 'management');

-- Endocrinology Questions
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('dka', 'A patient presents with DKA. What are the diagnostic criteria and initial fluid management?', 'Criteria: Glucose >250 mg/dL, pH <7.3, bicarbonate <18 mEq/L, positive ketones. Initial fluids: 0.9% saline 1-1.5 L in first hour, then 0.45% saline if sodium normal/high', 'management'),
('dka', 'What are the indications for starting insulin in DKA and what is the protocol?', 'Indications: After potassium >3.3 mEq/L. Protocol: Regular insulin 0.1 units/kg/hour continuous infusion, target glucose decrease 50-70 mg/dL per hour, add dextrose when glucose <250 mg/dL', 'management'),
('dka', 'A patient has type 2 diabetes with HbA1c of 9.5%. What is the recommended first-line medication regimen?', 'First-line: Metformin 500 mg BID with meals, titrate to 1000 mg BID as tolerated, add second agent (SGLT2 inhibitor, GLP-1 RA, or DPP-4 inhibitor) if HbA1c target not met in 3 months', 'management'),
('dka', 'What are the ACE/ARB recommendations for diabetic patients with albuminuria?', 'Recommendations: ACE inhibitor or ARB for any patient with albuminuria >300 mg/day or 30-300 mg/day with eGFR >60, titrate to maximum tolerated dose, monitor potassium and creatinine', 'management'),
('dka', 'A patient has hyperthyroidism with TSH <0.1 mIU/L and elevated free T4. What are the treatment options?', 'Options: Beta-blocker (propranolol 20-40 mg q6h) for symptoms, antithyroid drugs (methimazole 10-30 mg daily), radioactive iodine ablation, or thyroidectomy', 'management'),
('dka', 'What are the symptoms of hypoglycemia and what is the emergency management?', 'Symptoms: Adrenergic (tremor, anxiety, sweating), neuroglycopenic (confusion, seizure, coma). Emergency: If conscious - glucose tablets/juice, if unconscious - glucagon 1 mg IM or dextrose 50% IV', 'management'),
('dka', 'A patient has osteoporosis with T-score -2.8. What is the recommended treatment?', 'Treatment: Calcium 1200 mg daily, vitamin D 800-1000 IU daily, bisphosphonate (alendronate 70 mg weekly), weight-bearing exercise, fall prevention', 'management'),
('dka', 'What are the diagnostic criteria for metabolic syndrome?', 'Criteria (≥3 of 5): Waist circumference >102 cm (men) or >88 cm (women), triglycerides ≥150 mg/dL, HDL <40 mg/dL (men) or <50 mg/dL (women), BP ≥130/85, fasting glucose ≥100 mg/dL', 'data-interpretation'),
('dka', 'A patient has adrenal insufficiency. What are the signs of adrenal crisis and emergency treatment?', 'Crisis signs: Hypotension, hyponatremia, hyperkalemia, hypoglycemia, fever, abdominal pain. Emergency: Hydrocortisone 100 mg IV bolus then 50-100 mg q6-8h, fluid resuscitation with 0.9% saline, treat precipitating cause', 'management'),
('dka', 'What are the target HbA1c goals for different patient populations?', 'Targets: Most adults <7%, older adults with comorbidities <8%, young adults without complications <6.5% if achievable without hypoglycemia', 'management');

-- Haematology Questions
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('anaemia', 'A patient has microcytic anemia with iron studies showing low ferritin, low iron, high TIBC. What is the diagnosis and treatment?', 'Diagnosis: Iron deficiency anemia. Treatment: Oral ferrous sulfate 325 mg TID with vitamin C, treat underlying cause, repeat CBC in 4 weeks, continue 3-6 months after normalization', 'management'),
('anaemia', 'What are the causes of macrocytic anemia and what initial tests should be ordered?', 'Causes: B12 deficiency, folate deficiency, hypothyroidism, liver disease, alcohol, medications. Initial tests: B12 level, folate level, TSH, LFTs, review medications', 'data-interpretation'),
('anaemia', 'A patient has normocytic anemia with normal iron studies and low reticulocyte count. What is the differential diagnosis?', 'Differential: Anemia of chronic disease, renal failure, endocrine disorders, marrow failure, early iron deficiency. Next tests: CRP, creatinine, TSH, consider bone marrow biopsy', 'data-interpretation'),
('anaemia', 'What are the indications for red blood cell transfusion?', 'Indications: Hb <7 g/dL in stable patients, Hb <8 g/dL with cardiac disease, Hb <10 g/dL with active bleeding or symptoms, acute blood loss >30% blood volume', 'management'),
('anaemia', 'A patient has thrombocytopenia with platelet count 40,000. What are the common causes and when is treatment needed?', 'Causes: ITP, DIC, TTP/HUS, drug-induced, hypersplenism, marrow infiltration. Treatment needed for <10,000 or <50,000 with bleeding/active procedure', 'management'),
('anaemia', 'What are the WHO criteria for polycythemia vera diagnosis?', 'Criteria: Hb >16.5 g/dL (men) or >16.0 g/dL (women) OR Hct >49% (men) or >48% (women) PLUS presence of JAK2 mutation OR two minor criteria (subnormal EPO, bone marrow biopsy, endogenous erythroid colonies)', 'data-interpretation'),
('anaemia', 'A patient has elevated white blood cell count with left shift. What are the potential causes?', 'Causes: Leukemoid reaction (infection, inflammation, stress), chronic myeloid leukemia, leukoerythroblastosis, corticosteroids. Check for blasts, basophilia, splenomegaly', 'data-interpretation'),
('anaemia', 'What are the components of DIC workup and typical findings?', 'Workup: Platelet count, PT/INR, aPTT, fibrinogen, D-dimer. Findings: Low platelets, prolonged PT/aPTT, low fibrinogen, high D-dimer', 'data-interpretation'),
('anaemia', 'A patient has multiple myeloma. What are the CRAB criteria and what is the first-line treatment?', 'CRAB: HyperCalcemia, Renal insufficiency, Anemia, Bone lesions. First-line: Bortezomib-based regimen (bortezomib + lenalidomide + dexamethasone) for transplant-eligible, melphalan-based for transplant-ineligible', 'management'),
('anaemia', 'What are the indications for anticoagulation in atrial fibrillation?', 'Indications: CHA₂DS₂-VASc score ≥2 in men, ≥3 in women. Also consider anticoagulation for score 1 in men with additional risk factors', 'management');

-- Obs & Gynae Questions
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('obgyn', 'A pregnant woman at 20 weeks presents with vaginal bleeding. What are the differential diagnoses and initial management?', 'Differential: Threatened abortion, inevitable abortion, incomplete abortion, ectopic pregnancy (if <12 weeks), placenta previa, abruption. Management: Pelvic rest, ultrasound to determine location, avoid digital exam if previa suspected', 'management'),
('obgyn', 'What are the warning signs in pregnancy that require immediate evaluation?', 'Warning signs: Vaginal bleeding, decreased fetal movement, severe headache/visual changes, abdominal pain, fever, dysuria, swelling of face/hands, thoughts of self-harm', 'data-interpretation'),
('obgyn', 'A woman presents with secondary amenorrhea. What is the initial workup?', 'Workup: Pregnancy test, TSH, prolactin, FSH/LH, review medications, consider hypothalamic causes (stress, exercise, weight loss)', 'data-interpretation'),
('obgyn', 'What are the diagnostic criteria for PCOS?', 'Rotterdam criteria (2 of 3): Oligo/anovulation, clinical/biochemical hyperandrogenism, polycystic ovaries on ultrasound. Exclude other causes (thyroid, hyperprolactinemia)', 'data-interpretation'),
('obgyn', 'A postpartum woman has heavy vaginal bleeding. What are the common causes and initial management?', 'Causes: Uterine atony, retained placenta, genital tract trauma, uterine rupture, coagulopathy. Initial management: Fundal massage, oxytocin infusion, bimanual compression, consider surgical intervention', 'management'),
('obgyn', 'What are the risk factors for ectopic pregnancy and what are the classic symptoms?', 'Risk factors: Previous ectopic, PID, IUD use, tubal surgery, infertility. Symptoms: Amenorrhea, abdominal pain, vaginal spotting, adnexal mass, adnexal tenderness', 'data-interpretation'),
('obgyn', 'A woman has abnormal uterine bleeding. What is the PALM-COEIN classification?', 'PALM: Polyp, Adenomyosis, Leiomyoma, Malignancy/Hyperplasia. COEIN: Coagulopathy, Ovulatory dysfunction, Endometrial, Iatrogenic, Not yet classified', 'data-interpretation'),
('obgyn', 'What are the contraindications for combined oral contraceptive pills?', 'Contraindications: Age >35 with smoking, thromboembolism history, stroke/MI, estrogen-dependent tumors, active liver disease, pregnancy, uncontrolled hypertension', 'data-interpretation'),
('obgyn', 'A pregnant woman has gestational diabetes. What are the glucose targets and management approach?', 'Targets: Fasting <95 mg/dL, 1-hour postprandial <140 mg/dL, 2-hour <120 mg/dL. Management: Diet/exercise first, consider insulin or metformin if not controlled, monitor fetal growth', 'management'),
('obgyn', 'What are the signs of preterm labor and when is tocolysis indicated?', 'Signs: Regular uterine contractions >4 per hour, cervical change (dilation >2cm or effacement >80%). Tocolysis indicated <34 weeks with no contraindications to allow steroid administration', 'management');

-- Paediatrics Questions
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('paediatrics', 'A 2-year-old presents with fever, cough, and respiratory distress. What are the danger signs requiring immediate referral?', 'Danger signs: Unable to drink/breastfeed, vomiting everything, convulsions, lethargy/unconscious, chest indrawing, stridor, severe malnutrition, cyanosis', 'data-interpretation'),
('paediatrics', 'What is the management of acute watery diarrhea in children according to WHO guidelines?', 'Management: Plan A (no dehydration): ORS after each loose stool, zinc 20 mg daily for 14 days. Plan B (some dehydration): ORS 75 mL/kg over 4 hours. Plan C (severe): IV fluids urgently', 'management'),
('paediatrics', 'A child has suspected meningitis. What are the typical signs and empiric treatment?', 'Signs: Fever, headache, neck stiffness, photophobia, bulging fontanelle (infants), irritability, seizures. Empiric treatment: Ceftriaxone 100 mg/kg/day + vancomycin + dexamethasone before antibiotics', 'management'),
('paediatrics', 'What are the APLS (Advanced Pediatric Life Support) drug doses for cardiac arrest?', 'Doses: Adrenaline 10 mcg/kg (0.1 mL/kg of 1:10,000), Amiodarone 5 mg/kg, Atropine 20 mcg/kg, Glucose 10% 5 mL/kg, Fluid bolus 20 mL/kg', 'data-interpretation'),
('paediatrics', 'A 6-month-old infant has developmental delay. What are the red flags and initial evaluation?', 'Red flags: No social smile by 2 months, no sitting by 9 months, no babbling by 12 months, loss of skills. Evaluation: Detailed history, physical exam, hearing/vision screening, consider metabolic/genetic testing', 'data-interpretation'),
('paediatrics', 'What are the WHO criteria for severe malnutrition in children?', 'Criteria: Weight-for-height/length < -3 Z scores OR mid-upper arm circumference <115 mm OR presence of bilateral pitting edema', 'data-interpretation'),
('paediatrics', 'A child has acute asthma exacerbation. What are the severity classifications and treatment?', 'Mild: SpO2 >95%, able to talk - salbutamol 2-4 puffs. Moderate: SpO2 91-95, 1-2 word sentences - salbutamol + oxygen. Severe: SpO2 <91, can''t talk - continuous salbutamol, systemic steroids, consider ICU', 'management'),
('paediatrics', 'What are the common causes of failure to thrive and what is the initial workup?', 'Causes: Inadequate intake (feeding problems), increased losses (vomiting, malabsorption), increased requirements (cardiac, pulmonary), psychosocial. Workup: Detailed dietary history, growth chart, CBC, electrolytes, urine culture, consider sweat test', 'data-interpretation'),
('paediatrics', 'A neonate has jaundice. What are the risk factors for pathological jaundice and when is phototherapy indicated?', 'Risk factors: Prematurity, blood group incompatibility, cephalhematoma, infection, G6PD deficiency. Phototherapy: Bilirubin >15 mg/dL at 24-48h, >18 mg/dL at 49-72h, >20 mg/dL after 72h in term infants', 'management'),
('paediatrics', 'What are the immunization contraindications according to EPI schedule?', 'Absolute contraindications: Severe allergic reaction to previous dose, encephalopathy within 7 days of pertussis vaccine. Relative: Moderate/severe illness, immunosuppression (live vaccines)', 'data-interpretation');

COMMIT;
