-- OSCE Practice Cases - 30 cases across medical systems
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

-- Cardiology OSCE Cases
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('acs', 'Station: A 58-year-old man presents to emergency department with central chest pain radiating to left arm and jaw. Pain started 30 minutes ago at rest. He is diaphoretic and anxious. Vital signs: BP 160/90, HR 110, RR 24, SpO2 94% on room air. What are your immediate actions and differential diagnosis?', 'Immediate actions: ABCs, cardiac monitor, IV access, 12-lead ECG, aspirin 300mg chewable, nitroglycerin SL if no contraindications, oxygen if SpO2 <94%, morphine if pain persists. Differential: STEMI, NSTEMI, unstable angina, aortic dissection, pulmonary embolism, pericarditis', 'examination'),
('acs', 'Station: You are shown an ECG showing ST elevation in leads II, III, aVF with reciprocal ST depression in V1-V3. What is the diagnosis, which coronary artery is likely involved, and what is the management plan?', 'Diagnosis: Inferior wall STEMI. Likely involved: Right coronary artery (RCA) or left circumflex artery. Management: Activate cath lab, dual antiplatelet therapy (aspirin + ticagrelor 180mg), high-intensity statin, beta-blocker, ACE inhibitor, consider anticoagulation, prepare for PCI', 'data-interpretation'),
('dka', 'Station: A 65-year-old woman presents with palpitations for 2 hours. She feels light-headed but no chest pain. Past history: hypertension, type 2 diabetes. On examination: irregularly irregular pulse, HR 130, BP 140/80, lungs clear. What is the most likely diagnosis and what investigations would you order?', 'Most likely: Atrial fibrillation with rapid ventricular response. Investigations: 12-lead ECG to confirm, CBC, electrolytes, TSH, troponin, chest X-ray, echocardiogram to assess for structural heart disease and thrombus risk', 'examination'),
('stroke', 'Station: A 70-year-old man presents with sudden onset of right-sided weakness affecting face and arm, and speech difficulty. Symptoms started 90 minutes ago. On examination: right facial droop, right arm weakness 3/5, speech non-fluent but comprehension intact. NIHSS calculated as 8. What is your management plan?', 'Management: Immediate CT head to exclude hemorrhage, prepare for IV thrombolysis (alteplase) if no contraindications and within 4.5 hour window, blood pressure control if >185/110, admit to stroke unit, start secondary prevention', 'management'),
('anaemia', 'Station: A 45-year-old woman presents with fatigue and breathlessness on exertion for 3 months. Examination reveals pale conjunctiva, tachycardia 100, flow murmur at left sternal edge. CBC shows Hb 8.2 g/dL, MCV 68 fL, MCH 22 pg, platelets 450,000. What is the most likely diagnosis and what investigations would you order?', 'Most likely: Iron deficiency anemia. Investigations: Iron studies (ferritin, serum iron, TIBC), peripheral smear, stool for occult blood, consider endoscopy if age >50 with GI symptoms, gynecological evaluation if heavy menstrual bleeding', 'data-interpretation');

-- Respiratory OSCE Cases
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('pneumonia', 'Station: A 68-year-old man presents with 3-day history of fever, cough productive of rust-colored sputum, and right-sided chest pain worsened by breathing. He is a smoker with COPD. On examination: temperature 38.5°C, RR 28, SpO2 89% on room air, right lower lobe crackles, dullness to percussion. What is your assessment and management plan?', 'Assessment: Community-acquired pneumonia, CURB-65 score 3 (age >65, RR >30, confusion not present but SpO2 <90% = 1 point each). Management: Admit to hospital, IV antibiotics (ceftriaxone + azithromycin), oxygen therapy to maintain SpO2 ≥92%, IV fluids, monitor for complications', 'examination'),
('pneumonia', 'Station: You are shown a chest X-ray showing consolidation in the right lower lobe with air bronchograms and blunting of right costophrenic angle. What are the findings, what is the likely diagnosis, and what complication might be present?', 'Findings: Right lower lobe consolidation with air bronchograms and small right pleural effusion. Diagnosis: Right lower lobe pneumonia. Complication: Parapneumonic effusion, may require chest tube if large or infected', 'data-interpretation'),
('pneumonia', 'Station: A 25-year-old student presents with 1-week history of dry cough, headache, myalgias, and low-grade fever. On examination: temperature 37.8°C, scattered wheezes, normal vitals. CXR shows bilateral interstitial infiltrates. What is the likely diagnosis and treatment?', 'Likely diagnosis: Atypical pneumonia (Mycoplasma pneumoniae). Treatment: Oral macrolide (azithromycin 500mg daily for 5 days) OR doxycycline 100mg BID for 7 days, supportive care, follow up in 48-72 hours', 'management'),
('pneumonia', 'Station: A 35-year-old woman presents with acute shortness of breath and pleuritic chest pain. She is on oral contraceptive pills. On examination: tachycardia 110, RR 24, SpO2 91%, right leg swelling. What is your differential diagnosis and what investigation is most urgent?', 'Differential: Pulmonary embolism vs pneumonia vs pneumothorax. Most urgent: CT pulmonary angiogram (CTPA) to evaluate for PE. Consider D-dimer while waiting, start empiric anticoagulation if high suspicion', 'management'),
('pneumonia', 'Station: A 50-year-old man with known COPD presents with increased dyspnea and cough. He is using his inhalers more frequently. On examination: barrel chest, reduced breath sounds, wheezes bilaterally, SpO2 88% on room air. What are your immediate management steps?', 'Immediate steps: ABCs, high-flow oxygen to achieve SpO2 88-92%, nebulized salbutamol/ipratropium, systemic steroids (prednisone 40mg daily), consider non-invasive ventilation if worsening, assess for infection', 'management');

-- GI & Hepatology OSCE Cases
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('dka', 'Station: A 52-year-old alcoholic presents with hematemesis. He has vomited bright red blood three times in the last 2 hours. On examination: BP 90/60, HR 120, melena on rectal exam, spider angiomata, palpable liver. What is your immediate management?', 'Immediate management: ABCs, two large-bore IV cannulas, rapid fluid resuscitation with crystalloids, blood transfusion (type and cross), PPI infusion (omeprazole 80mg bolus then 8mg/hour), octreotide infusion, urgent gastroenterology consult for endoscopy', 'management'),
('dka', 'Station: A 40-year-old woman presents with right upper quadrant pain, fever, and jaundice. On examination: temperature 38.8°C, RUQ tenderness, Murphy''s sign positive. LFTs show bilirubin 4 mg/dL, ALP 450 U/L, AST 120 U/L. What is the likely diagnosis and what imaging would you order?', 'Likely diagnosis: Acute cholangitis (Charcot''s triad). Imaging: Right upper quadrant ultrasound first to look for gallstones and ductal dilation, then consider MRCP or ERCP if confirmed', 'examination'),
('dka', 'Station: A 35-year-old man presents with epigastric pain radiating to back, vomiting, and low-grade fever. He had a heavy meal last night. On examination: epigastric tenderness, guarding. Lipase is 800 U/L (normal < 200). What is the diagnosis and severity assessment?', 'Diagnosis: Acute pancreatitis. Severity assessment using Ranson criteria: At admission - check glucose, WBC, LDH, AST. This patient needs monitoring for systemic complications, likely moderate severity', 'data-interpretation'),
('dka', 'Station: A 45-year-old woman presents with chronic dyspepsia, weight loss, and early satiety. On examination: epigastric mass, palpable left supraclavicular node. What is your differential diagnosis and what investigations are essential?', 'Differential: Gastric cancer, peptic ulcer disease, lymphoma. Essential investigations: Upper GI endoscopy with biopsies, CT abdomen/pelvis for staging, CBC for anemia, tumor markers (CEA, CA 19-9)', 'examination'),
('dka', 'Station: A 30-year-old woman presents with bloody diarrhea, abdominal cramps, and fever for 3 days. She recently returned from travel. On examination: temperature 38.2°C, left lower quadrant tenderness. Stool shows blood and WBCs. What is the likely diagnosis and treatment?', 'Likely diagnosis: Inflammatory diarrhea (dysentery) - possibly Shigella or Campylobacter. Treatment: Supportive care, consider antibiotics if severe or high-risk (ciprofloxacin 500mg BID for 3 days), stool cultures, hydration', 'management');

-- Nephrology OSCE Cases
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('uti', 'Station: A 28-year-old woman presents with dysuria, frequency, urgency, and suprapubic pain for 2 days. She has no fever or flank pain. Urine dipstick shows 2+ leukocyte esterase, 2+ nitrites. What is the diagnosis and treatment?', 'Diagnosis: Uncomplicated cystitis. Treatment: Nitrofurantoin 100mg BID for 5 days OR TMP-SMX DS BID for 3 days OR fosfomycin 3g single dose, increased fluid intake, follow up if symptoms persist >48 hours', 'management'),
('uti', 'Station: A 65-year-old man with BPH presents with fever, chills, left flank pain, and nausea. On examination: temperature 39°C, left CVA tenderness, BP 100/60, HR 110. What is the diagnosis and what are the immediate management priorities?', 'Diagnosis: Complicated UTI/pyelonephritis with early sepsis. Immediate priorities: Blood cultures, urine cultures, IV fluids, empiric IV antibiotics (ceftriaxone 2g daily), monitor for septic shock, consider imaging for obstruction', 'management'),
('uti', 'Station: A 55-year-old diabetic patient presents with decreased urine output, swelling of legs, and shortness of breath. On examination: BP 180/100, pitting edema to knees, crackles at lung bases. Labs: creatinine 3.2 mg/dL (baseline 1.2), BUN 80 mg/dL. What is the diagnosis and initial management?', 'Diagnosis: Acute kidney injury likely due to contrast nephropathy or medication. Initial management: Stop nephrotoxic drugs, optimize volume status, avoid IV contrast, consider renal replacement therapy if volume overloaded or uremic, nephrology consultation', 'examination'),
('uti', 'Station: A 25-year-old woman presents with facial puffiness, foamy urine, and leg swelling. On examination: BP 140/90, pitting edema to mid-shin, proteinuria 4+ on dipstick. Labs: albumin 2.2 g/dL, total cholesterol 280 mg/dL. What is the likely diagnosis and what investigations are needed?', 'Likely diagnosis: Nephrotic syndrome. Investigations needed: 24-hour urine protein or protein/creatinine ratio, serum albumin, lipid profile, viral hepatitis screen, ANA, complement levels, consider renal biopsy', 'data-interpretation'),
('uti', 'Station: A 60-year-old man presents with hyperkalemia of 7.8 mEq/L. ECG shows peaked T waves and widened QRS. He is on ACE inhibitor for hypertension and has renal insufficiency. What is the emergency management?', 'Emergency management: Calcium gluconate 10% 10mL IV over 2-3 minutes (cardioprotection), then insulin 10 units with dextrose 50g IV, nebulized albuterol 10-20mg, sodium bicarbonate if acidotic, prepare for dialysis if refractory', 'management');

-- Neurology OSCE Cases
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('stroke', 'Station: A 70-year-old woman presents with sudden onset of confusion and right-sided weakness. Family found her unable to speak properly. On examination: aphasia, right facial droop, right arm and leg weakness, BP 170/90, HR 80. What is your immediate assessment and management?', 'Immediate assessment: ABCs, check blood glucose, calculate NIHSS, determine time of symptom onset. Management: Immediate CT head, prepare for thrombolysis if within window and no contraindications, admit to stroke unit', 'examination'),
('stroke', 'Station: You are shown a CT head showing hyperdense middle cerebral artery sign and loss of gray-white differentiation in left MCA territory. What are the findings, what is the diagnosis, and what is the significance?', 'Findings: Hyperdense MCA sign and early ischemic changes in left MCA territory. Diagnosis: Acute ischemic stroke, likely MCA occlusion. Significance: Large vessel occlusion, poor prognosis, candidate for mechanical thrombectomy within 6 hours', 'data-interpretation'),
('stroke', 'Station: A 22-year-old student presents with headache, fever, neck stiffness, and photophobia for 12 hours. On examination: temperature 38.5°C, positive Kernig and Brudzinski signs, petechial rash on legs. What is the likely diagnosis and what is the emergency management?', 'Likely diagnosis: Bacterial meningitis (possibly meningococcal given petechial rash). Emergency management: Blood cultures, lumbar puncture (after CT if indicated), start empiric ceftriaxone 2g IV + vancomycin + dexamethasone 10mg IV before antibiotics, isolation precautions', 'management'),
('stroke', 'Station: A 45-year-old woman presents with episodic throbbing headache associated with nausea, photophobia, and phonophobia. Attacks last 4-6 hours and are unilateral. What is the likely diagnosis and what are the preventive treatment options?', 'Likely diagnosis: Migraine without aura. Preventive options: Beta-blockers (propranolol), topiramate, amitriptyline, valproic acid. Acute treatment: NSAIDs, triptans, antiemetics', 'management'),
('stroke', 'Station: A 68-year-old man presents with resting tremor, slowness of movement, and shuffling gait. On examination: pill-rolling tremor, rigidity, bradykinesia, postural instability. What is the diagnosis and what are the first-line treatments?', 'Diagnosis: Parkinson''s disease. First-line treatments: Levodopa + carbidopa, dopamine agonists (pramipexole, ropinirole) for younger patients, MAO-B inhibitors (selegiline) for early disease, physical therapy', 'management');

-- Infectious Disease OSCE Cases
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('dengue', 'Station: A 25-year-old woman presents with 4-day history of high fever, severe headache, retro-orbital pain, and myalgia. On examination: temperature 39.5°C, positive tourniquet test, petechiae on arms. CBC shows platelets 80,000, hematocrit 45%. What is the diagnosis and what warning signs would make you admit?', 'Diagnosis: Dengue fever. Warning signs for admission: Severe abdominal pain, persistent vomiting, clinical fluid accumulation, mucosal bleeding, lethargy/restlessness, liver enlargement >2 cm, rapid increase in hematocrit with rapid decrease in platelets', 'examination'),
('dengue', 'Station: A patient with dengue fever develops severe abdominal pain and persistent vomiting. On examination: temperature 38°C, BP 90/60, HR 120, abdominal tenderness. CBC shows platelets 25,000, hematocrit 52%. What is the diagnosis and management?', 'Diagnosis: Dengue with warning signs progressing to severe dengue (possible plasma leakage). Management: Admit to hospital, IV fluid resuscitation with isotonic fluids, close monitoring of hematocrit and platelets, consider platelet transfusion if active bleeding', 'management'),
('typhoid', 'Station: A 30-year-old man presents with 10-day history of stepwise rising fever, headache, and constipation. On examination: temperature 39°C, relative bradycardia, splenomegaly, rose spots on abdomen. Widal test shows O 1:320, H 1:640. What is the diagnosis and treatment?', 'Diagnosis: Typhoid fever. Treatment: Admit, start ceftriaxone 2g IV daily OR cefixime 400mg orally BID for 14 days, supportive care, monitor for complications, consider azithromycin if resistant', 'management'),
('malaria', 'Station: A 35-year-old man returned from Chittagong Hill Tracts 10 days ago with fever, chills, and headache. On examination: temperature 40°C, jaundice, splenomegaly. Blood smear shows P. falciparum with parasitemia 6%. What is the severity and treatment?', 'Severity: Uncomplicated P. falciparum malaria (parasitemia <10%). Treatment: Artemether-lumefantrine 6-dose regimen over 3 days, take with food, monitor for treatment response, consider admission if unable to tolerate oral therapy', 'management'),
('cholera', 'Station: A 20-year-old woman presents with profuse watery diarrhea "rice-water stool" for 12 hours, vomiting, and leg cramps. On examination: severely dehydrated, sunken eyes, skin pinch goes back slowly, BP 80/50, HR 120. What is the diagnosis and emergency management?', 'Diagnosis: Cholera with severe dehydration. Emergency management: Immediate IV rehydration with Ringer lactate 100 mL/kg in first 3 hours (70 mL/kg in first hour), then ORS as tolerated, start antibiotics (doxycycline 300 mg single dose), zinc supplementation', 'management');

-- Endocrinology OSCE Cases
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('dka', 'Station: A 25-year-old known type 1 diabetic presents with nausea, vomiting, abdominal pain, and Kussmaul breathing. On examination: dehydrated, deep rapid breathing, fruity odor. Labs: glucose 450 mg/dL, pH 7.15, bicarbonate 12 mEq/L, ketones 3+. What is the diagnosis and initial management?', 'Diagnosis: Diabetic ketoacidosis. Initial management: ABCs, IV access, fluid resuscitation with 0.9% saline 1-1.5 L in first hour, start insulin infusion when potassium >3.3 mEq/L, monitor electrolytes and glucose closely', 'management'),
('dka', 'Station: A 55-year-old woman presents with weight gain, cold intolerance, and constipation. On examination: dry skin, hair loss, delayed deep tendon reflexes, bradycardia. Labs: TSH 25 mIU/L, free T4 0.5 ng/dL. What is the diagnosis and treatment?', 'Diagnosis: Hypothyroidism. Treatment: Levothyroxine replacement starting dose 1.6 mcg/kg/day (lower in elderly/ cardiac disease), titrate every 6-8 weeks based on TSH, patient education about lifelong therapy', 'management'),
('dka', 'Station: A 45-year-old man presents with polyuria, polydipsia, weight loss, and blurred vision. Random glucose is 280 mg/dL. What is the diagnostic criteria for diabetes and what initial management would you recommend?', 'Diagnostic criteria: Symptoms + random glucose ≥200 mg/dL OR fasting glucose ≥126 mg/dL OR 2-hour OGTT ≥200 mg/dL OR HbA1c ≥6.5%. Initial management: Metformin 500 mg BID with meals, lifestyle modification, HbA1c, lipid profile, renal function', 'management'),
('dka', 'Station: A 30-year-old woman presents with heat intolerance, tremor, weight loss despite increased appetite, and palpitations. On examination: tachycardia 110, fine tremor, mild proptosis, warm moist skin. Labs: TSH <0.01 mIU/L, free T4 3.5 ng/dL. What is the diagnosis and acute management?', 'Diagnosis: Hyperthyroidism (likely Graves disease). Acute management: Beta-blocker (propranolol 20-40 mg q6h) for symptoms, antithyroid drug (methimazole 10-30 mg daily), consider radioactive iodine ablation or thyroidectomy after stabilization', 'management'),
('dka', 'Station: A 60-year-old woman presents with bone pain and height loss. On examination: tenderness over thoracic spine. Labs: calcium 11.5 mg/dL, phosphorus 2.5 mg/dL, PTH 85 pg/mL (normal 10-65), vitamin D 15 ng/mL. What is the diagnosis and management?', 'Diagnosis: Primary hyperparathyroidism with vitamin D deficiency. Management: Surgical consultation for parathyroidectomy, vitamin D supplementation (cholecalciferol 1000 IU daily), ensure adequate hydration, monitor bone density', 'management');

-- Haematology OSCE Cases
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('anaemia', 'Station: A 35-year-old woman presents with fatigue, pallor, and pica. On examination: pale conjunctiva, koilonychia, glossitis. CBC shows Hb 7.8 g/dL, MCV 68 fL, MCH 22 pg, platelets 450,000. What is the most likely diagnosis and what investigations would confirm it?', 'Most likely diagnosis: Iron deficiency anemia. Confirmatory investigations: Iron studies (low ferritin <15 ng/mL, low serum iron, high TIBC >450 μg/dL, low transferrin saturation <15%), peripheral smear showing microcytic hypochromic RBCs', 'examination'),
('anaemia', 'Station: A 70-year-old man presents with fatigue and easy bruising. On examination: petechiae, ecchymoses, splenomegaly. CBC shows Hb 9.2 g/dL, WBC 15,000 with 40% blasts, platelets 45,000. What is the likely diagnosis and what is the emergency management?', 'Likely diagnosis: Acute leukemia (likely AML). Emergency management: Admit to hospital, urgent hematology consultation, tumor lysis syndrome prophylaxis (hydration, allopurinol), transfusion support, avoid leukapheresis unless WBC >100,000 with symptoms', 'management'),
('anaemia', 'Station: A 25-year-old woman presents with menorrhagia and fatigue. CBC shows Hb 9.5 g/dL, MCV 85 fL, platelets 350,000, WBC 8,000. Iron studies: ferritin 25 ng/mL, serum iron 60 μg/dL, TIBC 400 μg/dL. What type of anemia is this and what is the management?', 'Anemia type: Anemia of chronic disease with iron deficiency (mixed pattern). Management: Treat underlying cause of menorrhagia, oral iron supplementation, consider hormonal therapy for menstrual control, repeat CBC in 4-6 weeks', 'data-interpretation'),
('anaemia', 'Station: A 60-year-old man presents with left-sided headache, jaw claudication, and visual changes. On examination: tender temporal arteries, ESR 85 mm/hr. What is the diagnosis and what is the urgent management?', 'Diagnosis: Giant cell arteritis. Urgent management: Start high-dose prednisone 40-60 mg daily immediately (before temporal artery biopsy), arrange urgent ophthalmology review, schedule temporal artery biopsy within 1-2 weeks', 'management'),
('anaemia', 'Station: A 40-year-old woman presents with DVT in left leg. She is on oral contraceptives. What are her risk factors and what is the management?', 'Risk factors: Oral contraceptives, possible thrombophilia, immobility, obesity. Management: Start anticoagulation (LMWH bridge to warfarin with target INR 2-3 or DOAC), stop oral contraceptives, compression stockings, investigate for thrombophilia if recurrent', 'management');

-- Obs & Gynae OSCE Cases
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('obgyn', 'Station: A 28-year-old woman presents with amenorrhea for 8 weeks, nausea, and breast tenderness. On examination: blood pressure 120/80, uterus enlarged to 8 weeks size. What is the likely diagnosis and what investigations would you order?', 'Likely diagnosis: Pregnancy. Investigations: Urine pregnancy test (quick confirmation), quantitative serum β-hCG, pelvic ultrasound to confirm intrauterine pregnancy and gestational age, routine antenatal labs', 'examination'),
('obgyn', 'Station: A 32-year-old woman at 20 weeks gestation presents with vaginal bleeding. On examination: BP 110/70, fundal height 20 weeks, no abdominal tenderness, mild vaginal bleeding. What is the differential diagnosis and initial management?', 'Differential: Threatened abortion, placenta previa, abruptio placentae. Initial management: Pelvic rest, ultrasound to determine placenta location, avoid digital examination until placenta previa excluded, observe for increased bleeding', 'management'),
('obgyn', 'Station: A 24-year-old woman presents with lower abdominal pain and vaginal discharge for 3 days. On examination: lower abdominal tenderness, cervical motion tenderness, adnexal tenderness. Temperature 38°C. What is the likely diagnosis and treatment?', 'Likely diagnosis: Pelvic inflammatory disease. Treatment: Outpatient if mild-moderate: Ceftriaxone 500mg IM + doxycycline 100mg BID for 14 days. Inpatient if severe: IV cefoxitin + doxycycline, consider hospitalization if pregnant, immunocompromised, or failed outpatient therapy', 'management'),
('obgyn', 'Station: A 35-year-old woman presents with heavy menstrual bleeding lasting 7-10 days, passing large clots. CBC shows Hb 9.8 g/dL. What is the differential diagnosis and initial investigations?', 'Differential: Fibroids, adenomyosis, polyps, coagulopathy, ovulatory dysfunction, malignancy. Initial investigations: CBC, TSH, coagulation profile, pelvic ultrasound to evaluate uterus and endometrial thickness, consider endometrial biopsy if >35 or risk factors', 'data-interpretation'),
('obgyn', 'Station: A 30-year-old woman presents with infertility for 2 years. Menstrual cycles are regular every 35 days. On examination: normal findings. What investigations would you order for infertility workup?', 'Infertility workup: Day 3 FSH/LH, mid-luteal progesterone to confirm ovulation, hysterosalpingogram to check tubal patency, semen analysis for partner, TSH and prolactin, consider laparoscopy if indicated', 'management');

-- Paediatrics OSCE Cases
INSERT OR IGNORE INTO osce_cards (condition_id, question, answer, station_type) VALUES
('paediatrics', 'Station: A 2-year-old child presents with 3-day history of fever, cough, and poor feeding. On examination: temperature 39°C, RR 45, chest indrawing, SpO2 88% on room air, crackles on auscultation. What is the assessment and management?', 'Assessment: Severe pneumonia with hypoxemia. Management: Admit to hospital, oxygen therapy to maintain SpO2 ≥90%, IV antibiotics (ampicillin + gentamicin or ceftriaxone), monitoring, IV fluids if unable to drink, supportive care', 'examination'),
('paediatrics', 'Station: A 6-month-old infant presents with watery diarrhea for 2 days, no vomiting, able to breastfeed. On examination: weight 6 kg, alert, moist mucous membranes, skin pinch goes back immediately. What is the dehydration assessment and management?', 'Dehydration assessment: No dehydration (Plan A). Management: Continue breastfeeding, give ORS after each loose stool, zinc syrup 20 mg daily for 14 days, educate mother about danger signs, follow up in 2 days', 'management'),
('paediatrics', 'Station: A 3-year-old child presents with fever for 2 days and rash. On examination: temperature 38.5°C, maculopapular rash starting on face spreading to body, Koplik spots visible in mouth. What is the diagnosis and management?', 'Diagnosis: Measles. Management: Supportive care, vitamin A 200,000 IU orally daily for 2 days, isolate for 4 days after rash appears, monitor for complications (pneumonia, encephalitis), report to health authorities', 'management'),
('paediatrics', 'Station: A 1-month-old infant presents with poor feeding, lethargy, and fever 38°C. On examination: lethargic, fontanelle bulging, tachycardia 160, capillary refill 3 seconds. What is the assessment and emergency management?', 'Assessment: Neonatal sepsis with possible meningitis. Emergency management: ABCs, immediate IV access, blood cultures, lumbar puncture (if stable), start empiric antibiotics (ampicillin + gentamicin ± cefotaxime), admit to NICU, supportive care', 'management'),
('paediatrics', 'Station: A 4-year-old child presents with wheezing and cough for 2 days. History of similar episodes in past. On examination: diffuse wheezes, use of accessory muscles, SpO2 94% on room air. What is the diagnosis and acute management?', 'Diagnosis: Acute asthma exacerbation. Acute management: Salbutamol nebulization 2.5-5 mg every 20 minutes for 3 doses, systemic steroids (prednisolone 1-2 mg/kg), oxygen if SpO2 <94%, consider continuous nebulization if severe, admit if no improvement', 'management');

COMMIT;
PRAGMA foreign_keys=ON;
