declare module 'lucide-react' {
  export interface LucideIconProps {
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
    className?: string;
    style?: React.CSSProperties;
    children?: never;
  }

  export interface LucideIcon extends React.FC<LucideIconProps> {}

  export const Activity: LucideIcon;
  export const Airplay: LucideIcon;
  export const AlarmClockIcon: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const AlignCenter: LucideIcon;
  export const AlignJustify: LucideIcon;
  export const AlignLeft: LucideIcon;
  export const AlignRight: LucideIcon;
  export const ArrowDown: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const Baby: LucideIcon;
  export const Brain: LucideIcon;
  export const BadgeAlert: LucideIcon;
  export const Bold: LucideIcon;
  export const BookOpen: LucideIcon;
  export const Calendar: LucideIcon;
  export const CalendarDays: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const CheckSquare: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const ChevronsDownUp: LucideIcon;
  export const ChevronsUpDown: LucideIcon;
  export const CircleUserRound: LucideIcon;
  export const ClipboardCheck: LucideIcon;
  export const ClipboardList: LucideIcon;
  export const Cloud: LucideIcon;
  export const Code: LucideIcon;
  export const Copy: LucideIcon;
  export const Clock3: LucideIcon;
  export const Database: LucideIcon;
  export const Ear: LucideIcon;
  export const Fan: LucideIcon;
  export const FlaskConical: LucideIcon;
  export const GalleryHorizontal: LucideIcon;
  export const GraduationCap: LucideIcon;
  export const Heart: LucideIcon;
  export const Info: LucideIcon;
  export const Italic: LucideIcon;
  export const Lamp: LucideIcon;
  export const LayoutPanelLeft: LucideIcon;
  export const LifeBuoy: LucideIcon;
  export const ListTree: LucideIcon;
  export const LogOut: LucideIcon;
  export const Mail: LucideIcon;
  export const MenuSquare: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const Microscope: LucideIcon;
  export const MoonStar: LucideIcon;
  export const Pill: LucideIcon;
  export const Plus: LucideIcon;
  export const PlusCircle: LucideIcon;
  export const RefreshCcw: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const ScanLine: LucideIcon;
  export const Search: LucideIcon;
  export const Settings: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const Siren: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Stethoscope: LucideIcon;
  export const Sun: LucideIcon;
  export const Syringe: LucideIcon;
  export const Table: LucideIcon;
  export const Terminal: LucideIcon;
  export const Trophy: LucideIcon;
  export const Underline: LucideIcon;
  export const User2: LucideIcon;
  export const UserCheck: LucideIcon;
  export const UserPlus: LucideIcon;
  export const Users: LucideIcon;
  export const Wind: LucideIcon;
  export const X: LucideIcon;
  export const Zap: LucideIcon;
  export const Github: LucideIcon;
  export const AlertOctagon: LucideIcon;
}
