import { ClinicalShell } from "@/components/layout/ClinicalShell";
import { triggerSelectionHaptic } from "@/lib/clinical-haptics";
import {
  type RxDraft,
  clearDraft,
  getDraft,
  removeDrugFromDraft,
  updateDrugInDraft,
  updatePatientInfo,
} from "@/lib/prescription";
import { useFocusEffect } from "@react-navigation/native";
import { router } from "expo-router";
import { ArrowLeft, ClipboardCheck, Share2, Trash2 } from "lucide-react";
import { useCallback, useState } from "react";
import {
  Alert,
  ScrollView,
  Share,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";

export default function PrescriptionScreen() {
  const [draft, setDraft] = useState<RxDraft>(getDraft);

  useFocusEffect(
    useCallback(() => {
      setDraft(getDraft());
    }, []),
  );

  function refresh() {
    setDraft(getDraft());
  }

  function handleRemove(id: number) {
    removeDrugFromDraft(id);
    refresh();
  }

  function handlePatient(
    patch: Partial<
      Pick<RxDraft, "patientName" | "patientAge" | "patientSex" | "diagnosis">
    >,
  ) {
    updatePatientInfo(patch);
    setDraft((d) => ({ ...d, ...patch }));
  }

  function handleDrug(
    id: number,
    patch: Partial<{ dose: string; frequency: string; duration: string }>,
  ) {
    updateDrugInDraft(id, patch);
    setDraft((d) => ({
      ...d,
      drugs: d.drugs.map((dr) => (dr.id === id ? { ...dr, ...patch } : dr)),
    }));
  }

  async function handleShare() {
    triggerSelectionHaptic();
    const lines: string[] = [];
    lines.push("══════════════════════════════");
    lines.push("        PRESCRIPTION");
    lines.push("══════════════════════════════");
    if (draft.patientName) lines.push(`Patient : ${draft.patientName}`);
    if (draft.patientAge) lines.push(`Age     : ${draft.patientAge}`);
    if (draft.patientSex) lines.push(`Sex     : ${draft.patientSex}`);
    if (draft.diagnosis) lines.push(`Dx      : ${draft.diagnosis}`);
    lines.push("──────────────────────────────");
    draft.drugs.forEach((d, i) => {
      lines.push(
        `${i + 1}. ${d.brandName}${d.strength ? ` ${d.strength}` : ""}`,
      );
      if (d.genericName) lines.push(`   (${d.genericName})`);
      const sig = [d.dose, d.frequency, d.duration].filter(Boolean).join(" · ");
      if (sig) lines.push(`   ${sig}`);
    });
    lines.push("══════════════════════════════");
    lines.push("Generated by Clinical OS");

    try {
      await Share.share({ message: lines.join("\n") });
    } catch {
      // user dismissed
    }
  }

  function handleClear() {
    Alert.alert("Clear prescription", "Remove all drugs and patient info?", [
      { text: "Cancel", style: "cancel" },
      {
        text: "Clear",
        style: "destructive",
        onPress: () => {
          clearDraft();
          refresh();
        },
      },
    ]);
  }

  return (
    <ClinicalShell padded={false}>
      <View className="flex-1">
        {/* Header */}
        <View className="flex-row items-center px-4 pt-2 pb-4">
          <TouchableOpacity
            onPress={() => {
              triggerSelectionHaptic();
              router.back();
            }}
            className="mr-3 h-11 w-11 items-center justify-center rounded-2xl border border-border bg-ink-800"
          >
            <ArrowLeft size={21} color="#F5F5F7" strokeWidth={1.7} />
          </TouchableOpacity>
          <View className="flex-1">
            <Text className="font-heading text-[22px] text-text-primary">
              Prescription
            </Text>
            <Text className="font-body text-[12px] text-text-muted">
              {draft.drugs.length} drug{draft.drugs.length !== 1 ? "s" : ""}
            </Text>
          </View>
          {draft.drugs.length > 0 ? (
            <TouchableOpacity
              onPress={handleClear}
              className="mr-2 h-11 w-11 items-center justify-center rounded-2xl border border-border bg-ink-800"
              accessibilityLabel="Clear prescription"
            >
              <Trash2 size={17} color="#FF453A" strokeWidth={1.7} />
            </TouchableOpacity>
          ) : null}
          {draft.drugs.length > 0 ? (
            <TouchableOpacity
              onPress={handleShare}
              className="h-11 w-11 items-center justify-center rounded-2xl border border-mint bg-mint-soft"
              accessibilityLabel="Share prescription"
            >
              <Share2 size={17} color="#C8F53C" strokeWidth={1.7} />
            </TouchableOpacity>
          ) : null}
        </View>

        <ScrollView
          className="flex-1"
          contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 100 }}
          keyboardDismissMode="on-drag"
          keyboardShouldPersistTaps="handled"
        >
          {/* Patient info */}
          <Text className="mb-2 font-bodySemi text-[11px] uppercase tracking-[1.5px] text-text-muted">
            Patient
          </Text>
          <View className="mb-4 rounded-clinical border border-border bg-ink-800 p-4">
            <PatientField
              label="Name"
              value={draft.patientName}
              placeholder="Patient name"
              onChangeText={(v) => handlePatient({ patientName: v })}
            />
            <View className="flex-row gap-3">
              <View className="flex-1">
                <PatientField
                  label="Age"
                  value={draft.patientAge}
                  placeholder="e.g. 35y"
                  onChangeText={(v) => handlePatient({ patientAge: v })}
                />
              </View>
              <View className="flex-1">
                <PatientField
                  label="Sex"
                  value={draft.patientSex}
                  placeholder="M / F"
                  onChangeText={(v) => handlePatient({ patientSex: v })}
                />
              </View>
            </View>
            <PatientField
              label="Diagnosis"
              value={draft.diagnosis}
              placeholder="Clinical diagnosis"
              onChangeText={(v) => handlePatient({ diagnosis: v })}
              last
            />
          </View>

          {/* Drug list */}
          <Text className="mb-2 font-bodySemi text-[11px] uppercase tracking-[1.5px] text-text-muted">
            Drugs
          </Text>
          {draft.drugs.length === 0 ? (
            <View className="items-center rounded-clinical border border-border bg-ink-800 py-10">
              <ClipboardCheck size={32} color="#3A3A3F" strokeWidth={1.4} />
              <Text className="mt-3 font-bodySemi text-[14px] text-text-muted">
                No drugs added yet
              </Text>
              <Text className="mt-1 font-body text-[12px] text-text-muted">
                Search a drug in DIMS and tap "Add to prescription"
              </Text>
              <TouchableOpacity
                onPress={() => {
                  triggerSelectionHaptic();
                  router.push("/(tabs)/dims" as any);
                }}
                className="mt-4 rounded-pill bg-ink-700 border border-border px-5 py-2.5"
                activeOpacity={0.78}
              >
                <Text className="font-bodySemi text-[13px] text-mint">
                  Go to DIMS
                </Text>
              </TouchableOpacity>
            </View>
          ) : (
            draft.drugs.map((drug, idx) => (
              <View
                key={drug.id}
                className="mb-3 rounded-clinical border border-border bg-ink-800 p-4"
              >
                <View className="mb-3 flex-row items-start justify-between">
                  <View className="flex-1 pr-3">
                    <Text className="font-bodySemi text-[15px] text-text-primary">
                      {idx + 1}. {drug.brandName}
                      {drug.strength ? ` ${drug.strength}` : ""}
                    </Text>
                    {drug.genericName ? (
                      <Text className="mt-0.5 font-body text-[12px] text-text-muted">
                        {drug.genericName}
                        {drug.dosageForm ? ` · ${drug.dosageForm}` : ""}
                      </Text>
                    ) : null}
                  </View>
                  <TouchableOpacity
                    onPress={() => handleRemove(drug.id)}
                    hitSlop={10}
                    accessibilityLabel="Remove drug"
                  >
                    <Trash2 size={16} color="#FF453A" strokeWidth={1.6} />
                  </TouchableOpacity>
                </View>

                <View className="flex-row gap-2">
                  <SigField
                    label="Dose"
                    value={drug.dose}
                    placeholder="e.g. 500mg"
                    onChangeText={(v) => handleDrug(drug.id, { dose: v })}
                    flex={2}
                  />
                  <SigField
                    label="Frequency"
                    value={drug.frequency}
                    placeholder="1-0-1"
                    onChangeText={(v) => handleDrug(drug.id, { frequency: v })}
                    flex={2}
                  />
                  <SigField
                    label="Duration"
                    value={drug.duration}
                    placeholder="5 days"
                    onChangeText={(v) => handleDrug(drug.id, { duration: v })}
                    flex={2}
                  />
                </View>
              </View>
            ))
          )}

          {draft.drugs.length > 0 ? (
            <TouchableOpacity
              onPress={handleShare}
              className="mt-2 flex-row items-center justify-center gap-2 rounded-clinical border border-mint bg-mint-soft py-4"
              activeOpacity={0.78}
              accessibilityRole="button"
              accessibilityLabel="Share prescription"
            >
              <Share2 size={18} color="#C8F53C" strokeWidth={1.7} />
              <Text className="font-bodySemi text-[15px] text-mint">
                Share Prescription
              </Text>
            </TouchableOpacity>
          ) : null}
        </ScrollView>
      </View>
    </ClinicalShell>
  );
}

function PatientField({
  label,
  value,
  placeholder,
  onChangeText,
  last = false,
}: {
  label: string;
  value: string;
  placeholder: string;
  onChangeText: (v: string) => void;
  last?: boolean;
}) {
  return (
    <View className={`py-2.5 ${last ? "" : "border-b border-border-soft"}`}>
      <Text className="mb-1 font-body text-[11px] text-text-muted">
        {label}
      </Text>
      <TextInput
        value={value}
        onChangeText={onChangeText}
        placeholder={placeholder}
        placeholderTextColor="#505058"
        className="font-body text-[14px] text-text-primary"
        autoCorrect={false}
        selectionColor="#C8F53C"
      />
    </View>
  );
}

function SigField({
  label,
  value,
  placeholder,
  onChangeText,
  flex,
}: {
  label: string;
  value: string;
  placeholder: string;
  onChangeText: (v: string) => void;
  flex: number;
}) {
  return (
    <View className="flex-1 rounded-xl border border-border-soft bg-ink-700 px-3 py-2">
      <Text className="mb-1 font-body text-[10px] text-text-muted">
        {label}
      </Text>
      <TextInput
        value={value}
        onChangeText={onChangeText}
        placeholder={placeholder}
        placeholderTextColor="#505058"
        className="font-body text-[13px] text-text-primary"
        autoCorrect={false}
        selectionColor="#C8F53C"
      />
    </View>
  );
}
